config/routes.rb
Rails.application.routes.draw do
  resources :podcasts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
    has_one_attached :audio
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def podcast_params
      params.require(:podcast).permit(:title, :audio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusAudio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/podcasts/_form.html.erb
<%= form_with(model: podcast, local: true) do |form| %>
  <% if podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
        <% podcast.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :audio %>
    <%= form.file_field :audio %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Podcasts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @podcasts.each do |podcast| %>
      <tr>
        <td><%= podcast.title %></td>
        <td><%= podcast.duration %></td>
        <td><%= link_to 'Show', podcast %></td>
        <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
        <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Podcast', new_podcast_path %>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @podcast.title %>
</p>

<%= content_tag :div, data: { controller: 'audio',
                              target: 'audio.player',
                              'audio-url': url_for(@podcast.audio) } do %>
  <div class='controls'>
    <button class='btn btn-primary' data-action='audio#play' data-target='audio.play'>Play</button>
    <button class='btn btn-primary' data-action='audio#pause' data-target='audio.pause'>Pause</button>
  </div>
<% end %>

<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>